<a href="https://colab.research.google.com/github/Riturajkumari/Machine_learning/blob/main/Data_Encoding_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. What is data encoding? How is it useful in data science?**

- Models only work with numerical values.machines can't understand categorical data. Machines require all independent and dependent variables i.e input and output features to be numeric. For this reason, it is necessary to convert the categorical values of the features into numerical , This process of converting categorical data into numerical data is called **Encoding**.

The two most popular techniques of encoding are: 

- Nominal Encoding
- Ordinal Encoding

Ordinal Data: The categories have an inherent order

Nominal Data: The categories do not have an inherent order

convert these categorical variables to numbers such that the model is able to understand and extract valuable information.
data scientist of cleaning and preparing the data. And converting categorical data is an unavoidable activity. It not only elevates the model quality but also helps in better feature engineering.

**Q2. What is nominal encoding? Provide an example of how you would use it in a real-world scenario.**

Nominal data types in statistics are not quantifiable and cannot be measured through numerical units. Nominal types of statistical data are valuable while conducting qualitative research as it extends freedom of opinion to subjects.
- **nominal data type as we can’t compare with others.**
 
 *example*
 The color of a smartphone can be considered as a nominal data type as we can’t compare one color with others.

not possible to state that ‘Red’ is greater than ‘Blue’.

**Q3. In what situations is nominal encoding preferred over one-hot encoding? Provide a practical example.**

- One-Hot Encoding is the process of creating dummy variables.


- Any structured dataset includes multiple columns – a combination of numerical as well as categorical variables. A machine can only understand the numbers. It cannot understand the text. That’s essentially the case with Machine Learning algorithms.
- Categorical encoding is a process of converting categories to numbers.


In [ ]:
import sklearn.preprocessing as preprocessing
import numpy as np
import pandas as pd

targets = np.array(["red", "green", "blue", "yellow", "pink",
                    "white"])
labelEnc = preprocessing.LabelEncoder()
new_target = labelEnc.fit_transform(targets)
onehotEnc = preprocessing.OneHotEncoder()
onehotEnc.fit(new_target.reshape(-1, 1))
targets_trans = onehotEnc.transform(new_target.reshape(-1, 1))
print("The original data")
print(targets)
print("The transform data using OneHotEncoder")
print(targets_trans.toarray())

The original data
['red' 'green' 'blue' 'yellow' 'pink' 'white']
The transform data using OneHotEncoder
[[0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


C:\Users\Crl\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


**Q4. Suppose you have a dataset containing categorical data with 5 unique values. Which encoding
technique would you use to transform this data into a format suitable for machine learning algorithms?
Explain why you made this choice.**

**pandas categorical to numeric**
- pandas is by using the `pd.get_dummies()` method. It is a function in the Pandas library that can be used to perform one-hot encoding on categorical variables in a DataFrame.
- to use `OneHotEncoder` from the sklearn library, especially when you are doing machine learning tasks. 

In [ ]:
import pandas as pd

# generate df with 1 col and 4 rows
data = {
    "fruit": ["apple", "banana", "orange", "apple",'litchi']
}

# show head
df = pd.DataFrame(data)
df.head()

fruit
0   apple
1  banana
2  orange
3   apple
4  litchi

In [ ]:
# one-hot-encode using sklearn
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_results = encoder.fit_transform(df).toarray()
print(encoded_results)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


**Q5. In a machine learning project, you have a dataset with 1000 rows and 5 columns. Two of the columns
are categorical, and the remaining three columns are numerical. If you were to use nominal encoding to
transform the categorical data, how many new columns would be created? Show your calculations.**

In [32]:
import seaborn as sns
df=sns.load_dataset('dots')


In [33]:
df.head()

align choice  time  coherence  firing_rate
0  dots     T1   -80        0.0    33.189967
1  dots     T1   -80        3.2    31.691726
2  dots     T1   -80        6.4    34.279840
3  dots     T1   -80       12.8    32.631874
4  dots     T1   -80       25.6    35.060487

In [34]:
df.shape

(848, 5)

In [37]:
# getting categorical and numerical columns
cat_cols = df.select_dtypes(exclude='number').columns.to_list()
num_cols = df.select_dtypes(include='number').columns.to_list()

print('Categorical Columns: ', cat_cols)
print('Numerical Columns: ', num_cols)

Categorical Columns:  ['align', 'choice']
Numerical Columns:  ['time', 'coherence', 'firing_rate']


In [38]:
# values count categorical col
df['align'].value_counts()

sacc    454
dots    394
Name: align, dtype: int64

In [39]:
# values count categorical col
df['choice'].value_counts()

T2    430
T1    418
Name: choice, dtype: int64

In [40]:
# Label encoding
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()

In [41]:
df['align']= encoder.fit_transform(df['align'])


In [42]:
df['choice']= encoder.fit_transform(df['choice'])

In [44]:
df.head(5)

align  choice  time  coherence  firing_rate
0      0       0   -80        0.0    33.189967
1      0       0   -80        3.2    31.691726
2      0       0   -80        6.4    34.279840
3      0       0   -80       12.8    32.631874
4      0       0   -80       25.6    35.060487

**Q6. You are working with a dataset containing information about different types of animals, including their
species, habitat, and diet. Which encoding technique would you use to transform the categorical data into
a format suitable for machine learning algorithms? Justify your answer.**

In [107]:
# dataset 
data = pd.DataFrame({ 'specie' : ['dog', 'dog','cow'],
                       'habitat' : ['swamp','house','house'],
                        
                        'diet' :['chicken','chicken','grass'] })
data.head()

specie habitat     diet
0    dog   swamp  chicken
1    dog   house  chicken
2    cow   house    grass

In [108]:
# one-hot-encode using sklearn
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [112]:
df = pd.get_dummies(df, columns=[['specie','habitat','diet']])

KeyError: ignored

**Q7.You are working on a project that involves predicting customer churn for a telecommunications
company. You have a dataset with 5 features, including the customer's gender, age, contract type,
monthly charges, and tenure. Which encoding technique(s) would you use to transform the categorical
data into numerical data? Provide a step-by-step explanation of how you would implement the encoding.**

In [65]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({ 'gender' : ['Male', 'Female', 'Male', 'Female', 'Female'],
                       'Age' : [20,37,40,26,34],
                        'Monthly_charge' : [15000,40000,23000,28000,35000],
                        'tenure':['one yr','two yr','three yr','one yr','two yr']
                      })
df.head()

gender  Age  Monthly_charge    tenure
0    Male   20           15000    one yr
1  Female   37           40000    two yr
2    Male   40           23000  three yr
3  Female   26           28000    one yr
4  Female   34           35000    two yr

In [66]:
# getting categorical and numerical columns
cat_cols = df.select_dtypes(exclude='number').columns.to_list()
num_cols = df.select_dtypes(include='number').columns.to_list()

print('Categorical Columns: ', cat_cols)
print('Numerical Columns: ', num_cols)

Categorical Columns:  ['gender', 'tenure']
Numerical Columns:  ['Age', 'Monthly_charge']


In [67]:
# values count categorical col
df['gender'].value_counts()

Female    3
Male      2
Name: gender, dtype: int64

In [68]:
# values count categorical col
df['tenure'].value_counts()

one yr      2
two yr      2
three yr    1
Name: tenure, dtype: int64

In [69]:

from sklearn.preprocessing import OneHotEncoder

In [70]:
# create an instatance of one hot encoder
encoder = OneHotEncoder()

In [78]:
encoded = encoder.fit_transform(df[['gender','tenure']])


In [79]:
encoded_df=pd.DataFrame(encoded.toarray(), columns=encoder.get_feature_names_out())

In [80]:
encoded_df

gender_Female  gender_Male  tenure_one yr  tenure_three yr  tenure_two yr
0            0.0          1.0            1.0              0.0            0.0
1            1.0          0.0            0.0              0.0            1.0
2            0.0          1.0            0.0              1.0            0.0
3            1.0          0.0            1.0              0.0            0.0
4            1.0          0.0            0.0              0.0            1.0

In [77]:
df.head()

gender  Age  Monthly_charge    tenure
0    Male   20           15000    one yr
1  Female   37           40000    two yr
2    Male   40           23000  three yr
3  Female   26           28000    one yr
4  Female   34           35000    two yr

In [81]:
pd.concat([df,encoded_df], axis =1)

gender  Age  Monthly_charge    tenure  gender_Female  gender_Male  \
0    Male   20           15000    one yr            0.0          1.0   
1  Female   37           40000    two yr            1.0          0.0   
2    Male   40           23000  three yr            0.0          1.0   
3  Female   26           28000    one yr            1.0          0.0   
4  Female   34           35000    two yr            1.0          0.0   

   tenure_one yr  tenure_three yr  tenure_two yr  
0            1.0              0.0            0.0  
1            0.0              0.0            1.0  
2            0.0              1.0            0.0  
3            1.0              0.0            0.0  
4            0.0              0.0            1.0